### ISSUE TITLE
bug: VSCode "Debug test" fails to run test

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1048]
Using this version:

```bash
$ moon version --all
moon 0.1.20240926 (ab6f59e 2024-09-26) ~/.moon/bin/moon
moonc v0.1.20240927+a718e22cc ~/.moon/bin/moonc
moonrun 0.1.20240926 (ab6f59e 2024-09-26) ~/.moon/bin/moonrun
```

When I click on "Debug test" in VSCode, it prints this error:

```bash
/opt/homebrew/bin/node ./target/js/debug/test/flate.blackbox_test.cjs
Process exited with code 1
failed to parse args: "undefined" is not valid JSON
```

It looks like the generated test runner refers to `process.argv[2]` which does not exist since the test is being called with `node testfile.cjs`.

See screenshots:

![vscode-bug-debug-test-2024-09-27_09-24-28](https://github.com/user-attachments/assets/3e44fc0a-ccbd-4b3f-bbb9-26ed84dda09a)
![process argv-bug-2024-09-27_09-26-32](https://github.com/user-attachments/assets/7f9a25c2-d442-43b3-b897-f846f7849a69)

**Comment by bobzhang** [comment]
<img width="697" alt="Screenshot 2024-09-29 at 13 29 40" src="https://github.com/user-attachments/assets/7281737d-84f8-4e4a-97d7-44954943a753">

I came across the same issue when I was trying to  demo debug string_test

**Comment by hackwaly** [comment]
I guess it introduced by this commit https://github.com/moonbitlang/moon/commit/b214601a0cd9617332408b7303f9d307d17663f4#diff-8c340573be7bc677f6ff05c1ea7ef6d9dfa284093082fd19bad4b87872f782ee

Before this commit, test driver is able execute without cli arguments.

**Comment by hackwaly** [comment]
I don't understand why this tests get passed https://github.com/moonbitlang/moonbit-vsc-extension-check/actions/runs/11081995213

I'll dig it deeply later.

**Comment by hackwaly** [comment]
> I don't understand why these tests get passed https://github.com/moonbitlang/moonbit-vsc-extension-check/actions/runs/11081995213
> 
> I'll dig it deeply later.

It seems previous `test.yaml` accidentally cached the downloaded extension. I removed the cache config, so it reflects the latest nightly version of extension now.

**Comment by Young-Flash** [comment]
hi @gmlewis 
we have make a fix, use the latest toolchain should fix this
you can use `curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s` to install the latest toolchain

**Comment by gmlewis** [comment]
> we have make a fix, use the latest toolchain should fix this

That worked great... thank you!
Closing as fixed.
