### ISSUE TITLE
ArrayView should be able to grow if it stays within the bounds of its underlying buf

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1063]
Given an `ArrayView` of a small window within a larger `Array`, it should be possible to grow the size of the `ArrayView` either at the `start` or the `end` as long as it still remains within the bounds of the underlying `Array`.

For example, I would expect something like this to work:

```rust
test "arrayview grows within larger array" {
  let arr = [1, 2, 3, 4, 5, 6][2:4]
  inspect!(arr, content="[3, 4]")
  let arr = arr[:3]
  inspect!(arr, content="[3, 4, 5]")
  let arr = arr[:4]
  inspect!(arr, content="[3, 4, 5, 6]")
  let arr = arr[-1:4]
  inspect!(arr, content="[2, 3, 4, 5, 6]")
  let arr = arr[-1:5]
  inspect!(arr, content="[1, 2, 3, 4, 5, 6]")
}
```

**Comment by qazxcdswe123** [comment]
ArrayView works like a snapshot, so the view of another view operates on the previous **view** instead of the previous Array.

**Comment by gmlewis** [comment]
Locally, I've made my own `Slice` type based on `ArrayView` and changed one method and the above unit test passes (along with all the other existing `ArrayView` unit tests):

```rust
pub fn op_as_view[T](self : Slice[T], ~start : Int, ~end? : Int) -> Slice[T] {
  let len = self.buf.length()
  let end = match end {
    None => self.len
    Some(end) => end
  }
  guard self.start + start >= 0 && start <= end && end <= len else {
    abort("View start index out of bounds")
  }
  Slice::{ buf: self.buf, start: self.start + start, len: end - start }
}
```

**Comment by hackwaly** [comment]
What's the use cases? I can't see where need this. 

Align with go's slice is not our goal. In some language: `a.slice(-1, -2)` means `a.slice(a.length - 1, a.length - 2)`. So it may make users get confused.

**Comment by gmlewis** [comment]
> What's the use cases?

Here is an implementation of the LZW compression algorithm using [Slice](https://github.com/gmlewis/moonbit-flate/blob/c149acfed095d724a6926c68d9116caf564acf41/slice.mbt#L74-L84) as a replacement of [ArrayView](https://github.com/moonbitlang/core/blob/f3fd6c419d8d11b3a5ebefd0a8eaecc4310de031/builtin/arrayview.mbt#L71-L85):
https://github.com/gmlewis/moonbit-flate

Note that the only change I made to `ArrayView` was the change shown [above](https://github.com/moonbitlang/core/issues/1063#issuecomment-2399968746), along with its corresponding unit test, also shown [above](https://github.com/moonbitlang/core/issues/1063#issue-2571897010).

**Comment by hackwaly** [comment]
The underlying buffer of ArrayView is a snapshot of Array's backing FixedArray/UninitializedArray. So it may do not reflect the latest version of the Array. I guess that don't meet your need.

**Comment by gmlewis** [comment]
> For performance reason, the underlying buffer of ArrayView is a snapshot of Array's backing FixedArray/UninitializedArray. So it may not reflect the latest version of the Array, because Array may resize. I guess that don't meet your need.

Actually, I don't think it really matters what underlying buffer mechanism that `Array` is using.

As long as the underlying buffer is larger than the current `ArrayView`, my point is that it should not be an _ERROR_ to increase/grow the current `ArrayView` as long as it still stays within the bounds of the underlying buffer.

We don't have to _advertize_ that an `ArrayView` can grow, and it certainly may _NOT_ be common usage,
however it should _NOT_ be an _ERROR_ (like it currently is) to make it grow as long as it still stays within the bounds of its underlying buffer.

**Comment by hackwaly** [comment]
I know in Web API `Uint8Array` is a view for `ArrayBuffer`, and you can access it's buffer property to obtain the backing buffer. 

The key point to prevent it happen here is that the buffer of ArrayView is an internal type `UninitializedArray`. We have no plan to make it public to end users. So the ArrayView is a blackbox about it's buffer. You should not assume the length of the buffer.

You use case also not a common case. And you already find a workaround for it. It's not that bad compare to the solution of change the ArrayView.

**Comment by gmlewis** [comment]
> So the ArrayView is a blackbox about it's buffer.

Oh, OK.  Thanks.  Feel free to close then.

**Comment by hackwaly** [comment]
Correct me if I answered wrong. /cc @bobzhang

**Comment by gmlewis** [comment]
> So the `ArrayView` is a blackbox about it's buffer.

Actually, I'm not sure that this is true because my example within a local copy of this repo was able to calculate `buf.length()` and all the unit tests worked fine... so it appears that at the very least, the `length` of the underlying `buf` can be computed (which is the only piece of information that is needed, conveniently).

**Comment by hackwaly** [comment]
Your tests pass doesn't mean you can assume the length of buffer. For example: we might change the internal implementation to make the buffer a copy of slice if slice's length is small. We reserved many change possibility by hide the internal implementation.
