### ISSUE TITLE
`("/" : Json).stringify()` gets `"\/"`

### ISSUE THREAD

**Issue by lijunchen** [moonbitlang/core#1073]
Actually, two issues

- [x] The output of the following code is `"\/"`, but `"/"` is expected.
  will be fixed by https://github.com/moonbitlang/core/pull/1076

```
test {
  println(("/" : Json).stringify())
  // Output: "\/"
}
```

- [ ] `"\/"` is a valid JSON, but the lexer rejects it with the following error

```
test {
  let _ : Json = "\/"
}

Lexing error: invalid escape sequence: \/
```

**Comment by hackwaly** [comment]
>  "\/" is a valid JSON, but the lexer rejects it with the following error

Indeed "\/" is not a valid JSON.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/774337bf-14d6-458e-98e7-897e31a97d0e">

**Comment by Yoorkin** [comment]
related discussion #893, the default value of `~escape_slash` in Json::stringify is true

**Comment by Yoorkin** [comment]
> > "\/" is a valid JSON, but the lexer rejects it with the following error
> 
> Indeed "\/" is not a valid JSON.
> 
> <img alt="image" width="570" src="https://private-user-images.githubusercontent.com/540298/374860210-774337bf-14d6-458e-98e7-897e31a97d0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjA3NTEsIm5iZiI6MTcyODQ2MDQ1MSwicGF0aCI6Ii81NDAyOTgvMzc0ODYwMjEwLTc3NDMzN2JmLTE0ZDYtNDU4ZS05OGU3LTg5N2UzMWE5N2QwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwNzU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjM4ZDMwY2FjMjAxNzk5YTkwMzcyMWY1OTY5MTBhMGJkY2I5NmE3ZWQ4YzY4NTNlYTdmYTMzNTY2NTZiYWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2V2uoIY_iLjsRRM_1F7BzpT6r9G1KmqXN6XasN4A1Ek">

<img width="478" alt="image" src="https://github.com/user-attachments/assets/7c46f6b4-119e-4ed5-877e-d0f0188b5ea0">

`"\/"` is a valid json, but `\/` is not 😂
