### ISSUE TITLE
Do we need to make `escape_slash` default to `false` in `@json.stringify`?

### ISSUE THREAD

**Issue by lijunchen** [moonbitlang/core#1080]
Maybe we don't want to escape `"/"` to `"\/"` in most cases.

https://github.com/moonbitlang/core/issues/893
https://github.com/moonbitlang/core/issues/1073

**Comment by hackwaly** [comment]
Where we need escape "/"? IMO we can drop "/" escaping support, and provider some alternative functions to help escaping custom characters?

**Comment by bobzhang** [comment]
relevant:
https://stackoverflow.com/questions/35841447/force-json-stringify-to-escape-forward-slash-i-e
I agree it makes sense to change the default `escape_flash` to false
