### ISSUE TITLE
error: cannot add `moonbitlang/core` as dependency

### ISSUE THREAD

**Issue by jayphelps** [moonbitlang/core#109]
Tried to add the core library, but I receive a generic error. Not sure what to try. This is with the latest stable release of moon CLI.

<img width="462" alt="image" src="https://github.com/moonbitlang/moonbit-docs/assets/762949/6809fae9-9496-4bb7-9c42-f1d2adea7941">

```
$ moon add moonbitlang/core 

error: cannot add `moonbitlang/core` as dependency
```

Using a blank project created by `moon new`

**Comment by lijunchen** [comment]
The current `moonbitlang/core` and the compiler are released together and will be automatically linked during compilation. This means you do not need to install them from mooncakes.io. The `moonbitlang/core` on mooncakes.io currently serves only as documentation. We will fix the confusing installation information.

In the future, once the compiler reaches a stable state, it may allow for the addition of different versions of `moonbitlang/core`.

**Comment by jayphelps** [comment]
Can you clarify how to make it work? I tried to "just use" it but the compiler complains it can't find it. Latest version.

**Comment by lijunchen** [comment]
Below is my full installation log:

```
$ rm -rf ~/.moon
$ /bin/bash -c "$(curl -fsSL https://cli.moonbitlang.com/mac_m1_moon_setup.sh)"
Downloading https://cli.moonbitlang.com/macos_m1/moon to /Users/li/.moon/bin/moon
Downloading https://cli.moonbitlang.com/macos_m1/moonc to /Users/li/.moon/bin/moonc
Downloading https://cli.moonbitlang.com/macos_m1/moonfmt to /Users/li/.moon/bin/moonfmt
Downloading https://cli.moonbitlang.com/macos_m1/moonrun to /Users/li/.moon/bin/moonrun
Downloading https://cli.moonbitlang.com/macos_m1/moondoc to /Users/li/.moon/bin/moondoc
/Users/li/.moon/bin/moon downloaded
/Users/li/.moon/bin/moonc downloaded
/Users/li/.moon/bin/moonfmt downloaded
/Users/li/.moon/bin/moonrun downloaded
/Users/li/.moon/bin/moondoc downloaded
Update successfully!
Downloading moonbit core...
Install successfully
$ moon version --all
moon 0.1.0 (90245da 2024-03-22) ~/.moon/bin/moon
moonc 3592922 2024-03-22 ~/.moon/bin/moonc
$ moon new hello
Created hello
$ cd hello
$ moon run main
Hello, world!
```

What is your output?

**Comment by bobzhang** [comment]
@jayphelps note you don't need add core, you can use it directly
