### ISSUE TITLE
@immut/sorted_set should balance when the height diff larger or equal than 2

### ISSUE THREAD

**Issue by LittleJianCH** [moonbitlang/core#1123]
As title, AVL tree should do balance when height diff larger than 1. But the code in `immut/sorted_set/immutable_set.mbt` is 
```
fn balance[A : Compare](left : T[A], value : A, right : T[A]) -> T[A] {
  let left_height = left.height()
  let right_height = right.height()
  if left_height > right_height + 2 {
    match left {
...
```
I tried to modify it to `if left_height >= right_height + 2`, but there is no obvious performance improvement.
I'm not sure if it's necessary to fix.

**Comment by Lampese** [comment]
![image](https://github.com/user-attachments/assets/de7a4126-5ace-4455-8770-5c41712bcf8c)
The implementer @muqiuhan of this library should be using the ocaml base implementation of janestreet, and they have done the same.
