### ISSUE TITLE
Compiler bug: empty struct causes `Error [4014]`

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1146]
Bug demonstration:
https://github.com/gmlewis/moonbit-io/pull/1

**Comment by bobzhang** [comment]
note you can use `Struct::{}` to create an empty record, do you have realworld usage to use empty struct?

**Comment by gmlewis** [comment]
Ah, thank you, @bobzhang !
I'll try that out now.
Yes, my use case is linked above in the issue description.

**Comment by gmlewis** [comment]
That worked great, thank you, @bobzhang !
Closing as user error.
