### ISSUE TITLE
add pow for numbers

### ISSUE THREAD

**Issue by lijunchen** [moonbitlang/core#1161]
Int, Int64, Float, Double

**Comment by Lampese** [comment]
What about `UInt`, `UInt64`?

**Comment by lijunchen** [comment]
> What about `UInt`, `UInt64`?

Sure! I just forgot.

**Comment by Lampese** [comment]
The API type like `pow(n: Number(like Int,UInt),p: Double) -> Double` is a great design?

**Comment by Lampese** [comment]
- #1022 
I need it

**Comment by Lampese** [comment]
- #1284
