### ISSUE TITLE
bug report: mut check

### ISSUE THREAD

**Issue by He1pa** [moonbitlang/core#118]
I'm trying to implement a stable sorting algorithm. Is this error in the picture a bug? I changed the `runs` in the while block, but when defined with `mut`, an error will be prompted, and the `moon check` also failed
![image](https://github.com/moonbitlang/core/assets/56333845/7de0b74c-12ee-4e2d-906e-a7979dbe3acc)

**Comment by Yu-zh** [comment]
No, this is not a bug. You don't need `mut` on array type to mutate its elements. You only need `mut` when you want to mutate the array itself. The same applies to vector here.
