### ISSUE TITLE
sorted_set, hashset and buildin Set have different public interfaces

### ISSUE THREAD

**Issue by lgxbslgx** [moonbitlang/core#1190]
Currently, the `sorted_set`, `hashset` and buildin `Set` have different public functions. For example, the `sorted_set` has a function `add` in order to insert a element. But in `hashset` and buildin `Set`, the corresponding function name is `insert`. It is hard to change from one map to another. When I use `sorted_set` firstly and want to change it to `hashset`, I need to change all the inconsistent function names (for example : `add` -> `insert`).

**Comment by Lampese** [comment]
- #1113
