### ISSUE TITLE
How to get cli args in main()

### ISSUE THREAD

**Issue by trdthg** [moonbitlang/core#1205]
I don't know how to get args, it seems that there is no `@env` in both `moonbitlang/core` and `moonbitlang/x`.

After some searching, I find this usage: https://github.com/lijunchen/unstable-io-mbt#cli-args. However, it has been archived. So should I continue using this package, or is there other method?

**Comment by mengzhuo** [comment]
I think core team should add "peter-jerry-ye/wasi" as it's core

**Comment by Lampese** [comment]
> I think core team should add "peter-jerry-ye/wasi" as it's core

cc @peter-jerry-ye maybed add it to x?

**Comment by peter-jerry-ye** [comment]
It's not a good idea to add runtime dependent stuff to core/x.

**Comment by peter-jerry-ye** [comment]
https://github.com/moonbitlang/x/issues/71
