### ISSUE TITLE
Possible compiler bug - unreachable code for wasm and wasm-gc

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1219]
With this release of this repo: https://github.com/gmlewis/moonbit-io/releases/tag/v0.6.0
running the following works:

```bash
$ moon version --all
moon 0.1.20241111 (e6d64e0 2024-11-11) ~/.moon/bin/moon
moonc v0.1.20241111+dc2407357 ~/.moon/bin/moonc
moonrun 0.1.20241111 (e6d64e0 2024-11-11) ~/.moon/bin/moonrun
$ moon test --target js
Total tests: 38, passed: 38, failed: 0.
```

However, all of the other targets fail with "unreachable" or "panic":
* `moon test --target wasm`
* `moon test --target wasm-gc`
* `moon test --target native`

**Comment by peter-jerry-ye** [comment]
Minimal code to reproduce:
```
test "panic" {
  let empty : Array[Byte] = []
  let array : Array[Byte] = [1, 2, 3]
  empty.unsafe_blit(0, array, 0, 3) // wasm panic but not js
}

test "size" {
  let empty : Array[Byte] = Array::new(capacity=3)
  let array : Array[Byte] = [1, 2, 3]
  empty.unsafe_blit(0, array, 0, 3)
  inspect!(empty, content="[b'\\x01', b'\\x02', b'\\x03']") // js has content but wasm is empty
}

@hackwaly @Yu-zh 
```

**Comment by peter-jerry-ye** [comment]
So the panic is expected: `unsafe_blit` is expected to panic when the **length** is not enough. As the name suggest, it is `unsafe` so no extra check would be done.

The problem here is that the compiler should not use intrinsic instructions during debug/test mode, which we will fix it.

**Comment by gmlewis** [comment]
Ah!  So you are saying that the following is not correct:

```rust
pub fn write(self : Buffer, buf : Slice[Byte]) -> (Int, IOError?) {
  let cap = buf.length() + self.b.length()
  let b = Array::new(capacity=cap)
  Array::unsafe_blit(b, 0, self.b, 0, self.b.length())
  Array::unsafe_blit(b, self.b.length(), buf.buf, buf.start, buf.len)
  self.b = b
  (buf.length(), None)
}
```

I'll try using "push" instead of "unsafe_blit" and see if that fixes the problem.

**Comment by gmlewis** [comment]
Thank you for your help, @peter-jerry-ye !  I've now released version `v0.8.0` which fixes the `unsafe_blit` usage:
https://github.com/gmlewis/moonbit-io/releases/tag/v0.8.0

```
$ moon version --all
moon 0.1.20241111 (e6d64e0 2024-11-11) ~/.moon/bin/moon
moonc v0.1.20241111+dc2407357 ~/.moon/bin/moonc
moonrun 0.1.20241111 (e6d64e0 2024-11-11) ~/.moon/bin/moonrun
$ moon test --target all
Total tests: 39, passed: 39, failed: 0. [wasm-gc]
Total tests: 39, passed: 39, failed: 0. [wasm]
Total tests: 39, passed: 39, failed: 0. [js]
$ moon test --target native
Total tests: 26, passed: 26, failed: 0.
```

**Comment by gmlewis** [comment]
Here's one other unusual issue I found for target `native`:
https://github.com/gmlewis/moonbit-image/releases/tag/v0.5.0

```
$ moon version --all
moon 0.1.20241115 (67c2b06 2024-11-15) ~/.moon/bin/moon
moonc v0.1.20241115+351cfb074 ~/.moon/bin/moonc
moonrun 0.1.20241115 (67c2b06 2024-11-15) ~/.moon/bin/moonrun
$ moon test --target native
[======================================--] 29/30 done, 1/1 running
link-core: gmlewis/image/png_blackbox_test
failed to execute '/Users/glenn/src/github.com/gmlewis/moonbit-image/target/native/debug/test/png/png.blackbox_test.exe /Users/glenn/src/github.com/gmlewis/moonbit-image/target/native/debug/test/png/png.blackbox_test.exe'

Caused by:
    No such file or directory (os error 2)

Total tests: 26, passed: 16, failed: 10.
```

**Comment by peter-jerry-ye** [comment]
> I'm not sure if this is related, but target `wasm` is failing for this repo: https://github.com/gmlewis/moonbit-gzip/releases/tag/v0.16.0
> 
> but all other targets pass:
> 

The loopify optimization is off for debug mode. The test will pass if you test it under release mode:
`moon test --target wasm -p gmlewis/gzip -f gunzip_test.mbt -i 0 --release`

**Comment by peter-jerry-ye** [comment]
> Here's one other unusual issue I found for target `native`: https://github.com/gmlewis/moonbit-image/releases/tag/v0.5.0
> 

I found a bug with the code:
```moonbitlang
struct T {}

fn T::new() -> T! {
  if false {
    fail!("Error")
  }
  T::{  }
}

pub(open) trait Any {}

struct Test {
  f : () -> Any!
}

fn main {
  let _ : Test = { f: fn() { T::new!() } }

}
```

@Yu-zh 

But I didn't reproduce the one you described.

**Comment by peter-jerry-ye** [comment]
All the reproducible bugs are fixed. Feel free to reopen if any one still persists.

**Comment by gmlewis** [comment]
> All the reproducible bugs are fixed. Feel free to reopen if any one still persists.

Thank you, @peter-jerry-ye - I'm still having troubles with the `native` and `wasm` compiler targets.
See details here: https://github.com/gmlewis/moonbit-image/releases/tag/v0.12.0

**Comment by gmlewis** [comment]
Oh, and by the way, @peter-jerry-ye - it seems to me that being forced to add `as Image` should either be fixed in the compiler (so that it is not needed) or should be reported in the IDE from LSP as required, agreed?

Specifically, in the easier case, I had:

```moonbit
  let test_image : Array[Image] = [
    @image.RGBA64::new!(@image.rect(0, 0, 10, 10)),
    @image.NRGBA64::new!(@image.rect(0, 0, 10, 10)),
    @image.Alpha16::new!(@image.rect(0, 0, 10, 10)),
    @image.Gray16::new!(@image.rect(0, 0, 10, 10)),
  ]
```

and had to add `as Image` like this (or maybe this change was unnecessary now that I'm thinking about it more?):

```moonbit
  let test_image : Array[Image] = [
    @image.RGBA64::new!(@image.rect(0, 0, 10, 10)) as Image,
    @image.NRGBA64::new!(@image.rect(0, 0, 10, 10)) as Image,
    @image.Alpha16::new!(@image.rect(0, 0, 10, 10)) as Image,
    @image.Gray16::new!(@image.rect(0, 0, 10, 10)) as Image,
  ]
```

In the more complicated case, I had this:

```moonbit
struct TestT {
  name : String
  image : () -> Image!SizeError
}

let test_images : Array[TestT] = [
  {
    name: "rgba",
    image: fn() { @image.RGBA::new!(@image.rect(0, 0, 10, 10)) },
  },
...
```

and had to change it to this:

```moonbit
struct TestT {
  name : String
  image : () -> Image!SizeError
}

let test_images : Array[TestT] = [
  {
    name: "rgba",
    image: fn() { @image.RGBA::new!(@image.rect(0, 0, 10, 10)) as Image },
  },
...
```

If the compiler doesn't have enough information in this case, then maybe the LSP could sense this and let the user know that it is necessary to add the `as Image` ?

**Comment by peter-jerry-ye** [comment]
> > All the reproducible bugs are fixed. Feel free to reopen if any one still persists.
> 
> Thank you, @peter-jerry-ye - I'm still having troubles with the `native` and `wasm` compiler targets. See details here: https://github.com/gmlewis/moonbit-image/releases/tag/v0.12.0

Will look into it.

> If the compiler doesn't have enough information in this case, then maybe the LSP could sense this and let the user know that it is necessary to add the as Image ?

Sorry for the confusion @gmlewis. What I meant was that it was a compiler's bug that it didn't treat the promotion correctly. It was fixed in the previous releases, so now you can remove the `as Image`.
