### ISSUE TITLE
`@json.stringify` prints `NaN` for NaN double value

### ISSUE THREAD

**Issue by tonyfettes** [moonbitlang/core#1235]
Example to reproduce:

```moonbit
fn main {
  let a : Json = Number((-1.2).sqrt())
  println(@json.stringify(a)) // NaN
}
```

Some other programming languages:

| Language | Code | Output |
|----------|------|--------|
| JavaScript | `JSON.stringify(NaN)` | `null` |
| Python | `json.dumps(float('nan'))` | `NaN` |
| C (json-c) | `puts(json_object_to_json_string(json_object_new_double(NAN)))` | `NaN` |
| Rust | `serde_json::Value::Number(serde_json::Number::from_f64(f64::NAN).unwrap())` | panicked |

**Comment by hackwaly** [comment]
`NaN` is not a valid JSON value. `null` is right.

**Comment by tonyfettes** [comment]
Relavent cases:

- Infinity
- -Infinity

**Comment by tonyfettes** [comment]
On second thought this might be a backfire for scientific applications: they can't use JSONRPC simply because it won't emit/parse NaN and +-Inf.

Maybe we should use an option for it?

**Comment by peter-jerry-ye** [comment]
It's not our problem that they can't use JSON for RPC: it's due to JSON's design.

That's why JSON5 exists.
