### ISSUE TITLE
Feature request: turn off Warning [1002] for "Unused variable 'self'"

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1273]
As I write more packages, it has become apparent to me that it is frequently desirable to make methods satisfy a `Trait` which often requires not using the variable `self`.

However, this makes the output of the compiler extremely noisy (unnecessarily in my opinion).

So I would like to request that a special case be made for "Warning [1002]" where it will no longer report the warning for variable `self`.

**Comment by peter-jerry-ye** [comment]
You can always implement a method using `T::f` such as
```moonbit
fn T::f(_self : T, xxx : Int) -> Unit
```

or using explicit implelementation such as
```moonbit
impl Trait for Type with f(_self, xxx) {
}
```

In both cases, there's no need to declare the first variable as `self` to identify that it's a method.

With that said, what makes the `self` necessary? Can't you just ignore the `self` parameter?

**Comment by gmlewis** [comment]
I like your `T::f` solution a lot - thank you, @peter-jerry-ye !

To answer your questions, the best example I currently have is in my `gmlewis/image` package:
https://github.com/gmlewis/moonbit-image

where there are several traits like `Image` and `Color` that must be satisfied by many different structs for different image types and color models.  In many cases, the `trait` methods need to return constants to implement the trait, which doesn't need to use the `self` directly. However, I need the `self` to satisfy the `trait`, but I don't need to refer to it.

But of course, I could be missing something completely.  This is just my understanding.

I'm working now on getting rid of all the warnings in all my packages (including "gmlewis/image") using your `T::f` suggestion.

Closing feature request as unnecessary.  Thanks again, @peter-jerry-ye !
