### ISSUE TITLE
Errors publishing packages

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1277]
The following repos all generate the same error when publishing:

```
Finished. moon: no work to do
Check passed
error decoding response body: expected value at line 1 column 1
error: failed to run
```

* https://github.com/gmlewis/mbt-fonts-a
* https://github.com/gmlewis/mbt-fonts-b
* https://github.com/gmlewis/mbt-fonts-c
* https://github.com/gmlewis/mbt-fonts-d
* https://github.com/gmlewis/mbt-fonts-e
* https://github.com/gmlewis/mbt-fonts-f
* https://github.com/gmlewis/mbt-fonts-g
* https://github.com/gmlewis/mbt-fonts-h
* https://github.com/gmlewis/mbt-fonts-i
* https://github.com/gmlewis/mbt-fonts-j
* https://github.com/gmlewis/mbt-fonts-k
* https://github.com/gmlewis/mbt-fonts-l
* https://github.com/gmlewis/mbt-fonts-m
* https://github.com/gmlewis/mbt-fonts-n
* https://github.com/gmlewis/mbt-fonts-o
* https://github.com/gmlewis/mbt-fonts-p
* https://github.com/gmlewis/mbt-fonts-r
* https://github.com/gmlewis/mbt-fonts-s
* https://github.com/gmlewis/mbt-fonts-t
* https://github.com/gmlewis/mbt-fonts-u
* https://github.com/gmlewis/mbt-fonts-w

Only 4 repos published successfully:

* https://github.com/gmlewis/mbt-fonts-q
* https://github.com/gmlewis/mbt-fonts-v
* https://github.com/gmlewis/mbt-fonts-y
* https://github.com/gmlewis/mbt-fonts-z

Note that the successful ones are the four smallest repos, so I'm guessing the errors are related to the repo size.

**Comment by Young-Flash** [comment]
> error decoding response body

seems a network issue? how about retry `moon publish`

**Comment by lijunchen** [comment]
The issue occurred because Nginx has a default upload size limit of 1M (client_max_body_size). moon didn't gracefully handle the error raised by Nginx. For now, we've increased the upload limit on Nginx. However, please be aware that the mooncakes.io backend will still reject zip files larger than 16M.

**Comment by lijunchen** [comment]
@gmlewis I forgot to mention that we tweaked client_max_body_size to 32M, but the mbt-fonts-n.zip file is 73M, so the same error occurred😰. We'll improve the error message in the next release.

**Comment by gmlewis** [comment]
Thanks, @lijunchen - I tried to explain above, but wasn't terribly clear.

I tried deleting all the non-MoonBit JSON files before publishing, like so:

```bash
$ rm n*/n*json
$ moon publish
```

This should make a _much_ smaller ZIP file.

**Comment by lijunchen** [comment]
Got it! After deleting these JSON files, the zip file size is reduced to 36 MB.

```
$ moon package
$ du -h ./target/publish/gmlewis-fonts-n-0.2.0.zip
 36M    ./target/publish/gmlewis-fonts-n-0.2.0.zip
```

**Comment by gmlewis** [comment]
OK, so it looks like I'll have to delete some fonts or move them to another package.  Thanks again, @lijunchen !
