### ISSUE TITLE
`Double::op_mod` on Wasm backend produce JS-inconsistent result when the divisor is in subnormal range

### ISSUE THREAD

**Issue by tonyfettes** [moonbitlang/core#1303]
| Expression | Js | Wasm |
|------------|----|-----------|
| `5e-324 % 5e-324` | `0` | `-2.1219957905e-314` |
| `0.5 % 1.5e-323` | `1e-323` | `-3.5837322939398236e-299` |

**Comment by Lampese** [comment]
Actually, this error is acceptable for numerical algorithms... but for platformity, algorithms do need to be unified, and the priority may not be as high?
cc @tonyfettes

**Comment by liuly0322** [comment]
Hi everyone, I have just verified (from [the discussion](https://github.com/rustwasm/team/issues/84)) that rust-wasm is using [libm](https://github.com/rust-lang/libm) to standardize their math intrinsics, and their implementation is right (`5e-324 % 5e-324 == 0`), so the inconsistency is from the current MoonBit `fmod` implementation for non-js platforms.

IMO it's a bit more than just platformity, as many programming languages are using libm as their math library. We can refer to the libm to check the implementation of other math intrinsics too.

I'm going to open a PR to fix the current `fmod` algorithm soon, Thanks.

**Comment by tonyfettes** [comment]
@liuly0322 Sounds good, make sure to update NOTICE to include license from libm (and possibly from musl) as well.
