### ISSUE TITLE
Is it necessary to use the "open addressing" for `hashmap`?

### ISSUE THREAD

**Issue by FlyCloudC** [moonbitlang/core#1331]
The current `@core/hashmap.T` is using the "open addressing" with the Robin Hood method. Its structure looks like this:

```moonbit
struct T[K, V] {
  mut entries : FixedArray[Entry[K, V]?]
  ...
}
```

I was wondering if the moonbit compiler could implement `FixedArray[Entry?]` as a pointer to a flat Entry array. In other words, is it possible to "unbox" the Entry?

If it can't do that, then I think it would be better to use the “chaining method”, and define the entries as `FixedArray[List[Entry]]` instead. Because even with that change, **it wouldn't cost more space**, and make the implementation simpler.

The hash tables in the OCaml standard library also use the "chaining method".

**Comment by FlyCloudC** [comment]
A `ListEntry` is defined as a single object to save space

```moonbit
priv enum ListEntry[K, V] {
  Empty  Cons(
    key~ : K,
    hash~ : Int,
    mut value~ : V,
    mut next~ : ListEntry[K, V]
  )
}
```

There is an additional `next : ListEntry[K, V]` compared to the previous solution, but one less `psl : Int` (which is used by the Robin Hood method).

```moonbit
priv struct Entry[K, V] {
  mut psl : Int
  hash : Int
  key : K
  mut value : V
} derive(Show)
```

**Comment by Guest0x0** [comment]
Open addressing is actually faster, because chaining requires heap allocation, resulting in bad locality. Note that collision is **unavoidable** in hash table: even if we assume full hash value never collide, hash table entries will collide due to birthday paradox. In this case, open addressing gives better locality and hence better performance.

Most high performance hash tables use open addressing instead of chaining, including Swiss table and those in Facebook Folly. Since hash table is a very fundamental data structure, I think the performance gain is worth the extra code complexity

**Comment by Guest0x0** [comment]
oops, I missed your point of unboxing here. `Entry` cannot be unboxed currently, so there is indeed a performance issue here. In the future MoonBit may provide unboxing optimization for this kind of cases, but currently `Entry` cannot be unboxed, and the implementation here is not better than chaining.

A possible workaround is to use two separate arrays for keys and values. This may damage locality in some other cases, though.

**Comment by FlyCloudC** [comment]
> A possible workaround is to use two separate arrays for keys and values. This may damage locality in some other cases, though.
>
> some extra note here: one thing that blocks unboxing optimization is wasm-gc backend, it does not support this kind of "array of unboxed struct" pattern. So using two separate arrays for keys and values may be a more portable solution here. Benchmark is necessary on the performance impact though. Thanks for your feedback on this.

I get it. Thank you for your explanations and suggestions.
