### ISSUE TITLE
CompileError in backends

### ISSUE THREAD

**Issue by CAIMEOX** [moonbitlang/core#1376]
Using `rasie` in `while` loop causes weird compile error. First found in [quickcheck](https://github.com/moonbitlang/quickcheck/blob/5985baccca202abc2cca074be12d8ffc091c8291/src/lib/driver.mbt#L84) (The error messages of different backends are different) :
- wasm-gc
```
test moonbitlang/quickcheck/lib/driver_wbtest.mbt::... failed: RuntimeError: illegal cast
    at moonbitlang/quickcheck/lib.quick_check_with|Property| (wasm://wasm/0022eb6e:wasm-function[1217]:0x16771)
    at moonbitlang/quickcheck/lib.quick_check|Property| (wasm://wasm/0022eb6e:wasm-function[1228]:0x16d65)
    ....
```
- wasm
```
CompileError: WebAssembly.Module(): Compiling function #1238:"@moonbitlang/quickcheck/lib.State::run_test" failed: expected 1 elements on the stack for fallthru, found 2 @+116627
Failed to run the test: /home/caimeo/code/quickcheck/target/wasm/debug/test/lib/lib.whitebox_test.wasm
``` 
- js
```
... 
undefined
undefined
undefined
undefined
test moonbitlang/quickcheck/lib/driver_wbtest.mbt::prop reverse (fail) failed: TypeError: Cannot read properties of undefined (reading 'labels')
...
```

A simplified version is shown below: 
```moonbit
type! E String

pub fn woo() -> Int!E {
  while false {
    raise E("oh no")
  } else {
    1
  }
}
```
Calling the function `woo` gives the following results:
- js: works
- wasm-gc: `CompileError: WebAssembly.Module(): Compiling function #74:"username/hello/lib.woo" failed: struct.new[1] expected type i32, found struct.new of type (ref 45) @+6670`
- wasm: `Error: File "inlined_snapshot/_build/Transl_mtype.ml", line 85, characters 34-40: Assertion failed`

Notes:
- If the condition `false` in the while loop is changed to `true`, all backends behave well
- If the condition `false` in the while loop is changed to `get_true()`, where `fn get_true() { true }`, then the behavior of backends is the same as above.
- moon version: `0.1.20241219 (e628c26 2024-12-19)`

**Comment by Yu-zh** [comment]
Thanks for reporting this bug. This will be fixed in the next release. You can use for-loops to workaround this issue for now.
