### ISSUE TITLE
Bug: operator & can't being highlight normally as other operator such as operator +

### ISSUE THREAD

**Issue by KCN-judu** [moonbitlang/core#1384]
![0D936E7B9C63297A982315C8A6A95A1F](https://github.com/user-attachments/assets/6af9f7d2-21f8-4558-8564-8a98dd31fb8e)

**Comment by KCN-judu** [comment]
it happens in other bitwise operators too.
such as operator |, ^

**Comment by Lampese** [comment]
https://github.com/moonbitlang/moonbit-tmLanguage
