### ISSUE TITLE
json: should us merge True and False?

### ISSUE THREAD

**Issue by Lampese** [moonbitlang/core#1391]
Now we have a JSON defination:

```moonbit
pub(all) enum Json {
  Null
  True
  False
  Number(Double)
  String(String)
  Array(Array[Json])
  Object(Map[String, Json])
} derive(Eq)
```

But when I want to match json with a key typed Bool, I faced a small problem:

```moonbit
let {"somekey":Bool(somekey), ...other keys pattern matching} = json
```

And I must to deal True and False separately so I cannot add it to my pattern matching.

Should us merge True and False to Bool(Bool)?

**Comment by peter-jerry-ye** [comment]
```moonbit
let { "someKey" : True | False as somekey, ... other keys pattern matching } = json
let somekey = somekey == True
```

**Comment by Lampese** [comment]
> ```moonbit
> let { "someKey" : True | False as somekey, ... other keys pattern matching } = json
> let somekey = somekey == True
> ```

oh, that's a better way.
