### ISSUE TITLE
Vec::iter_revi semantics seem uninutitive

### ISSUE THREAD

**Issue by bobzhang** [moonbitlang/core#144]
1. the name may look better like `iter_revi`
2. `i` for the first itered element is not 0 but the `length - 1`, is this the correct behavior?

**Comment by Lampese** [comment]
In terms of iteration order, `i` should start at 0, but in terms of the index of the array, `i` should start at `length - 1`. Which of these two is better?

**Comment by bobzhang** [comment]
suppose you have fold_lefti, fold_righti, both are expected to start from 0

**Comment by CAIMEOX** [comment]
> In terms of iteration order, `i` should start at 0, but in terms of the index of the array, `i` should start at `length - 1`. Which of these two is better?

OCaml (Jane Street) base library takes the former one [list.ml](https://github.com/janestreet/base/blob/043ffd4c30b1712590b5207c386c9e68d6bfe32b/src/list.ml#L534) .
