### ISSUE TITLE
Dependency circle misjudged

### ISSUE THREAD

**Issue by Lampese** [moonbitlang/core#154]
[Here](https://github.com/Lampese/core/tree/show) I have imported `list` using `vec` and imported `vec` using `list`, but the compiler gives me the error `error: cyclic dependency detected in package moonbitlang/core/option`.

 For this reason, I mapped the whole set of dependencies to check and found that `option` has no dependency on them.
```mermaid
graph LR
assertion --> deque
assertion --> array
assertion --> bytes
assertion --> coverage
assertion --> double
assertion --> hashmap
assertion --> immutable_hashmap
assertion --> immutable_set
assertion --> map
assertion --> int
assertion --> int64
assertion --> list
assertion --> math
assertion --> queue
assertion --> priority_queue
assertion --> id(option)
style id fill:#bbf,stroke:#f66,stroke-width:2px,color:#fff,stroke-
double --> math
string --> coverage
math --> array
num --> double
num --> int
num --> int64
int --> hashmap
list --> hashmap
list --> immutable_hashset
array --> list
array --> hashmap
array --> immutable_hashmap
array --> immutable_set
vec --circle--> list
vec --> map
list --> map
assertion --> ref
num --> ref
int --> ref
assertion --> result
list --> stack
array --> stack
assertion --> stack
assertion --> strconv
assertion --> tuple
assertion --> vec
string --> vec
list --circle--> vec
```

**Comment by CAIMEOX** [comment]
This error seems to be somewhat random. 
It reports `error: cyclic dependency detected in package moonbitlang/core/tuple` in my machine

**Comment by Lampese** [comment]
To make debugging easier, I wrote a [tool](https://github.com/Lampese/moonbit-tree) to draw a dependency graph.

**Comment by lijunchen** [comment]
should be fixed https://github.com/moonbitlang/core/actions/runs/8516746347/job/23326246867?pr=185
