### ISSUE TITLE
Coverage should be smarter

### ISSUE THREAD

**Issue by Lampese** [moonbitlang/core#223]
- [x] The `test` block should not be counted as coverage.
- [ ] There are some `abort` statements that will never run, is there a way to ignore them?

**Comment by lynzrand** [comment]
> The test block should not be counted as coverage.

This should be already solved after a recent compiler update.

**Comment by jialunzhang-psu** [comment]
```moonbit
pub fn MutableSet::singleton[T : Compare](value : T) -> MutableSet[T] {
  {    root: Some(
      {
        color: Black,
        left: None,
        value: Some(value),
        right: None,
        parent: None,
      },
    ),
    size: 1L,
  }
}

**Comment by lynzrand** [comment]
> For this snippet of code, the Codecov bot literally comments that the second line is not covered by tests, but not on any other lines. What causes such behavior? It can be found in #269 
> ```moonbit
> pub fn MutableSet::singleton[T : Compare](value : T) -> MutableSet[T] {
>   {    
>     root: Some(
>       {
>         color: Black,
>         left: None,
>         value: Some(value),
>         right: None,
>         parent: None,
>       },
>     ),
>     size: 1L,
>   }
> }
> ```

Seems like you didn't test this particular function in your test cases. You can use this function in your test cases like `MutableSet::singleton(...)` and it should be covered.

**Comment by jialunzhang-psu** [comment]
> > For this snippet of code, the Codecov bot literally comments that the second line is not covered by tests, but not on any other lines. What causes such behavior? It can be found in #269
> > ```
> > pub fn MutableSet::singleton[T : Compare](value : T) -> MutableSet[T] {
> >   {    
> >     root: Some(
> >       {
> >         color: Black,
> >         left: None,
> >         value: Some(value),
> >         right: None,
> >         parent: None,
> >       },
> >     ),
> >     size: 1L,
> >   }
> > }
> > ```
> 
> Seems like you didn't test this particular function in your test cases. You can use this function in your test cases like `MutableSet::singleton(...)` and it should be covered.

Sorry for not making myself clear. What I meant was sometimes Codecov report covers some lines of the basic block (e.g. [line 223](https://github.com/moonbitlang/core/pull/249/files)), and often the times it covers only the first line of the basic block. What causes this?

**Comment by lynzrand** [comment]
> Sorry for not making myself clear. What I meant was sometimes Codecov report covers some lines of the basic block (e.g. [line 223](https://github.com/moonbitlang/core/pull/249/files)), and often the times it covers only the first line of the basic block. What causes this?

I see what you mean. In fact, the coverage instrumentation is branch-based instead of line-based, i.e. each instrumentation spot represents a whole branch taken. However, due to certain limitations of the current coverage report system, each branch is only represented by its starting position in the report. Thus, you will see the coverage line reports only at the start of blocks.

Making the instrumentation point in the coverage report span the whole block instead of just the starting point is indeed a good enhancement idea. We will consider adding it in the future.

**Comment by jialunzhang-psu** [comment]
> Thus, you will see the coverage line reports only at the start of blocks.

I get that. But why does Codecov report cover the entire basic block from time to time, rather than always the entry point of the basic block? I am just curious what could cause such discrepancies.

**Comment by Lampese** [comment]
I think the second suggestion is not related about coverage, so I'll close this issue then.

cc @lynzrand
