### ISSUE TITLE
Question about array out-of-bound checking

### ISSUE THREAD

**Issue by lgxbslgx** [moonbitlang/core#289]
Hi all,

I added the `+ 1` to the function `Array::iter` to trigger the out-of-bound error. But all the tests passed locally (x86 & Linux). Whether the compiler do such check? Or is it a bug?

```
 /// @intrinsic %array.iter
 pub fn iter[T](self : Array[T], f : (T) -> Unit) -> Unit {
-  for i = 0; i < self.length(); i = i + 1 {
+  for i = 0; i < self.length() + 1; i = i + 1 {
     f(self[i])
   }
 }
```

Best Regards,
-- Guoxiong

**Comment by CAIMEOX** [comment]
It seems that the compiler uses **builtin intrinsic** by default. Actually this code won't be executed even if you write:
```moonbit
pub fn iter[T](self : Array[T], f : (T) -> Unit) -> Unit {}
```
all tests can also be completed.

**Comment by lgxbslgx** [comment]
> It seems that the compiler uses **builtin intrinsic** by default. Actually this code won't be executed even if you write:
> 
> ```
> pub fn iter[T](self : Array[T], f : (T) -> Unit) -> Unit {}
> ```
> 
> all tests can also be completed.

It seems you are right. I added `debug("test")` to the begining of the function `Array::iter`, but the message can't be printed.

**Comment by hackwaly** [comment]
The body of function which marked`@intrinsic` said it's default implementation. Compiler may not use default implementation if it found builtin platform specific implementation.

So, we might need provide a cli option to config to force use default implementation of specified intrinsic.

**Comment by bobzhang** [comment]
we will disable @intrinsic in debug mode

**Comment by lgxbslgx** [comment]
Thanks for your answers.
