### ISSUE TITLE
Weird warning message

### ISSUE THREAD

**Issue by yj-qin** [moonbitlang/core#304]
I got a weird warning message when running `moon check` on [this commit](https://github.com/moonbitlang/core/pull/292/commits/54599019dcb4f9b1e55766b994ea9123417c4011)
```
:0:0-0:0 Warning 010: Unused pattern
:0:0-0:0 Warning 012: Unreachable code
```

**Comment by bobzhang** [comment]
cc @Guest0x0

**Comment by bobzhang** [comment]
should be fixed in master
