### ISSUE TITLE
Rename deque to devec

### ISSUE THREAD

**Issue by Lampese** [moonbitlang/core#343]

**Comment by blqis** [comment]
Hi, me and @al-humea would like to work on this if possible

**Comment by Lampese** [comment]
> Hi, me and @al-humea would like to work on this if possible. Should the other related repositories have it renamed as well?

Where are you referring to other repo? Is it from other folders?

**Comment by Lampese** [comment]
> Hi, me and @al-humea would like to work on this if possible. Should the other related repositories have it renamed as well?

Oh? Are you referring to those users who have already started using it? Indeed, they need to make changes because the core API is still in an unstable stage, and users need to bear the risk of these consistency issues. If you're talking about something else, you can add it.

**Comment by blqis** [comment]
I meant the entirety of the moonbitlang project, including the course, documentation and such. So as to have consistent naming across all files.

And thank you for letting us work on this!

**Comment by Lampese** [comment]
> I meant the entirety of the moonbitlang project, including the course, documentation and such. So as to have consistent naming across all files.
> 
> And thank you for letting us work on this!

Oh... as far as I know, this part may not have been used by those yet, so I should only focus on the core part.

**Comment by blqis** [comment]
You're right, thank you.

I've noticed a deque is often called "dq", would it make sense to change the variable name into "dv" ?

**Comment by Lampese** [comment]
> You're right, thank you.
> 
> I've noticed a deque is often called "dq", would it make sense to change the variable name into "dv" (to reference devec)?

just do it.

**Comment by blqis** [comment]
It is now done and we've opened a pull request. We made sure to make separate commits for each type of rename just in case. :)

**Comment by Lampese** [comment]
done in #357.
