### ISSUE TITLE
provide a fast Vec::of_array for most general cases using blit

### ISSUE THREAD

**Issue by bobzhang** [moonbitlang/core#368]
We are working on improve the cases like `Vec:[1,2,3] // Syntactic array`, this is not common once we switched literal syntax for Vec, however, convert arbitrary array into vec still needs to be improved (using array.copy intrinsics provided by wasmgc)

**Comment by hackwaly** [comment]
Complete in https://github.com/moonbitlang/core/pull/566/files#diff-acc21918bc4fd893932049c31941e1bb51f47be542aeafd5b7f075ada0b07afcR24-R30
