### ISSUE TITLE
[Proposal] Naming for iter 

### ISSUE THREAD

**Issue by hackwaly** [moonbitlang/core#407]
`as_iter` -> `iter`
`iter` -> `for_each`

```
[1, 2, 3, 4, 5]
  .iter()
  .for_each(fn { it => print(it) })
```

**Comment by bobzhang** [comment]
iter
each ?

**Comment by shamiao** [comment]
vote `.iter()` & `.each(f)`. This allows the term 'iter' indicates `@iter.Iter` types without ambiguity.
