### ISSUE TITLE
[moon build system] bug: improper default value in `license` field in `moon.mod.json`

### ISSUE THREAD

**Issue by shamiao** [moonbitlang/core#437]
`moon new` will make an empty project which is licensed under `"license": "Apache-2.0"`.  This is just bad, since users doesn't release their source code under any license implied.

It's suggested that license field has a proper default value like `NO-LICENSE-APPLIED`, `TO-BE-FILLED-BY-OWNER` etc.

The task of preventing non-free source code should be accomplished by <https://mooncakes.io/> registry. It's the registry's job to reject any non SPDX identifier license field when users publish their mooncakes.

**Comment by peter-jerry-ye** [comment]
The default should be empty now.
