### ISSUE TITLE
Language server needs to show argument names in addition to their types

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#479]
When attempting to get more information about a particular method, the help text pops up in VSCode but only shows the types of the arguments and doesn't show the names, but then the text below refers to the argument names.  Both are needed.

For example:

![missing-info-2024-05-31_15-27-24](https://github.com/moonbitlang/core/assets/6598971/3df6fb4c-844f-43fd-9c2d-1009ca275b7a)

In this case, the signature of `blit` is displayed as: `(Int, Bytes, Int, Int) -> Unit`
but it should instead be shown as: 

```
blit(
  self : Bytes,
  dst_offset : Int,
  src : Bytes,
  src_offset : Int,
  length : Int
) -> Unit
```

so that the developer can figure out how to call the method.

**Comment by bzy-debug** [comment]
It should be able to print parameter names now.

Close as completed. Feel free to reopen it when you run into any problems.

**Comment by gmlewis** [comment]
Note that this still seems to be a problem.

In my opinion, the following display for `trim` is not helpful because I have no idea what the second parameter should be without going to this repo and looking up the source code for the `trim` function:

<img width="1102" alt="unhelpful-tooltip-2024-11-29_10-07-54" src="https://github.com/user-attachments/assets/3e88e727-e53d-4feb-8027-0e26a405a05b">
