### ISSUE TITLE
Compiler generates "(result i32)" for host functions returning "-> Unit"

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#503]
I'll add more details here in a few hours.

**Comment by gmlewis** [comment]
In this repo: https://github.com/gmlewis/moonbit-pdk/tree/master
when I type:

```bash
$ moon update && moon install
$ moon build --target wasm --output-wat
```

The resulting WAT file as the following definitions for host functions:

```wat
(func $extism:host/env.alloc.3 (import "extism:host/env" "alloc") (param i64)
 (result i64))
(func $extism:host/env.store_u8.2 (import "extism:host/env" "store_u8")
 (param i64) (param i32) (result i32))
(func $extism:host/env.input_load_u8.5
 (import "extism:host/env" "input_load_u8") (param i64) (result i32))
(func $extism:host/env.config_get.9 (import "extism:host/env" "config_get")
 (param i64) (result i64))
(func $extism:host/env.var_get.10 (import "extism:host/env" "var_get")
 (param i64) (result i64))
(func $extism:host/env.output_set.7 (import "extism:host/env" "output_set")
 (param i64) (param i64) (result i32))
(func $extism:host/env.length.8 (import "extism:host/env" "length")
 (param i64) (result i64))
(func $extism:host/env.free.0 (import "extism:host/env" "free") (param i64)
 (result i32))
(func $extism:host/env.var_set.11 (import "extism:host/env" "var_set")
 (param i64) (param i64) (result i32))
(func $extism:host/env.log_debug.1 (import "extism:host/env" "log_debug")
 (param i64) (result i32))
(func $extism:host/env.load_u8.4 (import "extism:host/env" "load_u8")
 (param i64) (result i32))
(func $extism:host/env.input_length.6
 (import "extism:host/env" "input_length") (result i64))
```

However, their definitions are found here: https://github.com/gmlewis/moonbit-pdk/blob/39754f0e61c0d717bbc5d18291cf229f439b5d30/pdk/env.mbt#L33-L39
and many of these functions have a void (`-> Unit`) return type and the `(result i32)` should be completely removed.

Currently, I've written a workaround Go script that fixes the WAT file then converts the WAT to WASM by calling `wat2wasm`. The script is located here:
https://github.com/gmlewis/moonbit-pdk/blob/master/cmd/install-spectest-shim/main.go

Please let me know if you need more detail.

**Comment by peter-jerry-ye** [comment]
This is the expected behavior because in the functional programming language, all expressions has a value. And here the value has type of `Unit` here and it is represented by `i32`.

We have special treatment for the imported functions, i.e. the return type can be ignored (remove the `-> Unit`, it's only allowed for FFIs) and then the `(result i32)` will be removed. With that said, we have no special treatment for the exported functions yet...

**Comment by gmlewis** [comment]
Thank you, @peter-jerry-ye !
I'm working around a different problem now, but will close this one since you gave me the answer.
