### ISSUE TITLE
A single Random state

### ISSUE THREAD

**Issue by bobzhang** [moonbitlang/core#514]
currently the random package has two type 

```
struct RandomInt {
  state : FixedArray[Int]
  mut index : Int
}

struct RandomInt64 {
  state : FixedArray[Int64]
  mut index : Int
}
```
It would be nice to use only one type `RandomState`, so that we have 

```
let default : RandomState  =  ...
pub fn init_state(...) {
}
```
In this case, it is convenient to use the API without passing around the seed why keep it flexible to 
seed the random package

**Comment by bobzhang** [comment]
cc @Lampese

**Comment by Lampese** [comment]
LGTM, and in fact, mt19937 is too slow, and most requirements don't need to be so strict. We have discussed before that the random provided by the compiler or using simpler random algorithms are necessary.

Unfortunately, I have been busy preparing for the NEMT recently and currently do not have time to complete this part of the writing.
