### ISSUE TITLE
Cannot test non pub functions in xxx.test.mbt in same package

### ISSUE THREAD

**Issue by hackwaly** [moonbitlang/core#555]

**Comment by shemasultana69** [comment]
=========================================

[✅√📺📱👉🔴 Click Here To XVIDEOS XNXX Video](https://t.co/3KYzxozio1)

[✅√📺📱👉🔴 Click Here To XVIDEOS XNXX Video](https://t.co/3KYzxozio1)

========================================

Please use the sharing tools found via the share button at the top or side of articles. Copying articles to share with others is a breach of FT.com T&Cs and Copyright Policy. to buy additional rights. Subscribers may share up to 10 or 20 articles per month using the gift article service. More information can be found at

Three of the world’s biggest pornography sites will be hit with new regulatory curbs including stricter requirements on age verification, after EU regulators determined the adult platforms fell within the scope of a landmark law designed to police content online.

Xvideos, Pornhub and Stripchat will be from April subject to the obligations of “very large online platforms” under the Digital Services Act (DSA), according to three people familiar with the move.

That designation applies to platforms with more than 45mn users and has so far been applied to tech groups such as Facebook, Wikipedia and TikTok.

The adult websites caught by the legislation will be forced to comply with a series of stringent measures, including being forced to apply systems that can verify the age of users, according to people familiar with the plans.

Other measures include new responsibilities to take down illegal content such as non-consensual videos, and becoming subject to external audits to ensure they comply with rules. An announcement on the EU’s decision is expected on Wednesday.

The three online porn platforms are among some of the world’s most visited sites. Xvideos alone has 160mn monthly visitors in the bloc, according to people familiar with EU regulators’ analysis, representing about a third of EU citizens.

Companies that fail to follow the new EU digital rules face fines of up to 6 per cent of their global turnover.

Canada-based Pornhub said it had only 33mn users in the EU and did not meet the DSA’s threshold. Stripchat, as well as Prague-headquartered Xvideos, did not respond to requests for comment.

The DSA represents a landmark overhaul of the bloc’s digital rules. It sets new standards for policing hate speech, disinformation and counterfeits online for large digital platforms. In April, the European Commission designated a total of 19 companies with special obligations under the law.

EU regulators have used the law to open an official probe into Elon Musk’s X over its record of policing content related to the Israel-Hamas conflict, and have sent requests to TikTok and YouTube to provide more information on their methods in regards to policing content

Thierry Breton, the EU commissioner in charge of implementing the DSA, said: “I have been very clear that creating a safer online environment for our children is an enforcement priority under the DSA.”

Regulators across the world have struggled to police so-called user-generated sites, which rely on individuals to post content and have been criticised for harbouring harmful and illegal material.

Porn sites have proven particularly difficult to rein in, as most of the large so-called tube sites, such as Pornhub and Xvideos, are owned by a handful of secretive companies.

Please use the sharing tools found via the share button at the top or side of articles. Copying articles to share with others is a breach of FT.com T&Cs and Copyright Policy. Email to buy additional rights. Subscribers may share up to 10 or 20 articles per month using the gift article service. More information can be found at
