### ISSUE TITLE
[proposal] make name of new/make function consistent

### ISSUE THREAD

**Issue by Yoorkin** [moonbitlang/core#582]
Currently, there are various functions to construct the value of some types in moonbitlang/core:

- `T::new()` `T::make()`: create a new collection without any arguments
- `T::with_capacity(capacity : Int)`, `T::make(capacity : Int)`, `T::new(~capacity)`: create a new collection with an initial capacity.
- `T::make(Int,T)` `T::new(Int,T)`: create a new collection with N initial elements.
- `T::make(Int,() -> T)`: create a new collection with N initial elements, all generated by a callback.
- `T::new_with_index(Int,(Int) -> T)`: create a new collection with n initial elements, each generated by the callback with an index parameter.

# Proposed Naming Convention

- Part 1. Use `T::new()`, `T::new(~capacity)`, `T::new(...)` for:
    - Mutable collection types to create a new, empty collection without any argument, or with just one optional capacity argument.
    - Types with only one `new/make` function, e.g. `Rational::new(Int64,Int64)`
    
- Part 2. Use `T::make(Int,T)`, `T::make_with(Int,() -> T)`, `T::make_with_index(Int, (Int) -> T)` for:
    - Collection types to return a new instance with N initial elements, where the elements can be generated by callback function. e.g. `Array::make(Int,T)` `Bytes::make(Int, ~initial)`

**Comment by qazxcdswe123** [comment]
What could be the difference between `Bytes::new(Int, ~initial)` and `T::make(Int,T)`?

**Comment by Yoorkin** [comment]
> What could be the difference between `T::new(...)` (like `Bytes::new(Int, ~initial)`) and `T::make(Int,T)`?
> 


Some mutable collections like Array, there are functions such as `new(~capacity)` and `make(Int, T)`, Since function overloading is not allowed, they must have different names.  For types that have only one `new/make` function, and the function type does not resemble `f(Int, T) -> Self`, `f(Int, () -> T) -> Self`, or `f(Int, (Int) -> T) -> Self`, I suggest using the name `new` to ensure that the IDE completion can always provide a "constructor" when the user types `T::new`.

> I'd suggest we only keep
> 
> `make` -> `T::make_with(Int,() -> T)` and `makei` -> `T::make_with_index(Int, (Int) -> T)`
> 
> which is also analogous to `map` and `mapi`

The `make(Int,T)` and `make(Int,() -> T)` is difference because the elements of first one are physically equal.

**Comment by qazxcdswe123** [comment]
For 0 or 1 arguments, use `new`.
For 2 arguments, use `make`.

For standard library, user should able to "guess" what they are looking for, thus consistency > correctness, even consistently wrong! @bobzhang

**Comment by qazxcdswe123** [comment]
`make_with_index/capacity`
- [ ] deuqe
- [ ] array
- [ ] immut/array

---

- [ ] UninitializedArray::make

---

- [ ] arraycore: make_uninit -> new_uninit

**Comment by Yoorkin** [comment]
per discussion with @bobzhang, for part 2, we will remove APIs like `make_with` and rename `make_with_index` to `makei` to align with `map/mapi`.
