### ISSUE TITLE
[proposal]: Add `DefaultMap[K,V]` or `Map[K,V]::set_default` like in Python

### ISSUE THREAD

**Issue by KKKIIO** [moonbitlang/core#588]
Currently, there is no concise way to set a default value for a key in `Map[K,V]`. The `Map::get_or_default` method returns the default value without updating the map. This makes tasks like word counting more verbose.

I propose adding a `Map::set_default` method that updates the map with the default value and returns it if the key does not exist.

Alternatively, a `DefaultMap[K,V]` could be introduced to automatically create entries for missing keys. This would be particularly useful if it follows a standard `Map` trait.

**Comment by bobzhang** [comment]
> I propose adding a Map::set_default method that updates the map with the default value and returns it if the key does not exist.

This looks good to me

**Comment by hackwaly** [comment]
As my experience, `DefaultMap` and `MultiMap` is more useful than set_default

**Comment by KKKIIO** [comment]
I prefer `set_default` (or [merge](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#merge-K-V-java.util.function.BiFunction-) if possible). In my experience, `set_default` is primarily used during the building phase. For the rest of the time, sticking to get ensures safety.
