### ISSUE TITLE
Inappropriate parentheses removed

### ISSUE THREAD

**Issue by Lampese** [moonbitlang/core#632]
Before format:
```moonbit
test "panic op_get" {
  @deque.Deque::[1, 2, 3][-1] |> ignore
  (@deque.Deque::[1, 2, 3])[-1] |> ignore
}
```
then:
```moonbit
test "panic op_get" {
  @deque.Deque::[1, 2, 3][-1] |> ignore
  @deque.Deque::[1, 2, 3][-1] |> ignore
}
```
Based on the feedback I received on the coverage tool, the results obtained from these two writing methods are different, but the formatting tool removed parentheses for them.

**Comment by qazxcdswe123** [comment]
Thank you for the report. This is an oversight, but we are deprecating the syntax `T::[]` so this shouldn't be an issue.
