### ISSUE TITLE
Feature Request: @json.JsonValue.as_integer()

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#651]
I'm writing a code generator, and it would be really nice to have a new `as_integer()` method on a `@json.JasonValue` in addition to `as_number()` because I'm finding myself having to write stuff like this all over the place:

```rust
pub fn User::from_json(value : @json.JsonValue) -> User? {
  let value = value.as_object()?
  let age = match value.get("age") {
    Some(jv) =>
      match jv.as_number() {
        Some(n) => Some(n.to_int())
        None => None
      }
    None => None
  }
```

**Comment by bobzhang** [comment]
hi @gmlewis , we have very good support for json pattern matching, for exmaple,
```
match value {
  { "age" : Some (Number n) } => n.to_int()
  _ => None  
}
```

**Comment by gmlewis** [comment]
OK, thanks... I probably just haven't figured out the best ways to code yet in MoonBit.

**Comment by gmlewis** [comment]
@bobzhang - could you please give me some guidance on the best way to convert this `@json.JsonValue` to a `struct`?

I've currently got:

```rust
/// `AllThree` represents a JSON object with all three array types.
pub struct AllThree {
  ints : Array[Int]
  floats : Array[Double]
  strings : Array[String]
} derive(Debug, Eq, Show)


/// `all_three_object` tests passing an object of all three arrays.
pub fn all_three_object() -> Int {
  let s = @host.input_string()
  let jv = try {
    @json.parse!(s)
  } catch {
    e => {
      @host.set_error("unable to parse input: \(e)")
      return 1 // failure
    }
  }
  //
  let all_three : AllThree = match jv {
    Object(
      {
        "ints": Some(Array(ints)),
        "floats": Some(Array(floats)),
        "strings": Some(Array(strings)),
      }
    ) => {
      let ints : Array[Int] = ints.map(fn { n => n.as_number() }).filter(
        fn { n => not(n.is_empty()) },
      ).map(fn { n => n.unwrap().to_int() })
      let floats : Array[Double] = floats.map(fn { n => n.as_number() }).filter(
        fn { n => not(n.is_empty()) },
      ).map(fn { n => n.unwrap() })
      let strings : Array[String] = strings.map(fn { n => n.as_string() }).filter(
        fn { n => not(n.is_empty()) },
      ).map(fn { n => n.unwrap() })
      { ints, floats, strings }
    }
    _ => {
      @host.set_error("unable to parse input: \(s)")
      return 1 // failure
    }
  }
  //
  let result = process_all_three(all_three)
  //
  let jv = @jsonutil.to_json(result)
  @host.output_json_value(jv)
  0 // success
}
```

but I'm thinking that there must be a better way that I'm missing.

This also doesn't catch errors in the arrays... so if I passed `"ints":[0,1,2,'THREE']` it would silently ignore the string within the ints.

Thank you!

**Comment by bobzhang** [comment]
> could you please give me some guidance on the best way to convert this @json.JsonValue to a struct?

We plan to provide a deriving mechanism for JSON, but we are not there yet. 
For raw json processing, we will provide first class support (probably this week)

**Comment by bobzhang** [comment]
@gmlewis https://github.com/moonbitlang/core/pull/757/files let me know if it helps

**Comment by gmlewis** [comment]
> @gmlewis https://github.com/moonbitlang/core/pull/757/files let me know if it helps

That is helpful and looks good, but I would really like to see how you hand this case, if you have a moment, please:

```rust
/// `AllThree` represents a JSON object with all three array types.
pub struct AllThree {
  ints : Array[Int]
  floats : Array[Double]
  strings : Array[String]
} derive(Eq, Show)
```

**Comment by bobzhang** [comment]
> This also doesn't catch errors in the arrays... so if I passed "ints":[0,1,2,'THREE'] it would silently ignore the string within the ints.

Is this what you worried? I think you can either raise an error immediately or collect those invalid results and report them all together.

Did I miss anything?

**Comment by bobzhang** [comment]
@gmlewis I wrote a small example, hope it helps https://github.com/moonbitlang/core/pull/767/files
note we are fleshing out the error handling, so the error handling part still need some tweaks

**Comment by gmlewis** [comment]
> @gmlewis I wrote a small example, hope it helps https://github.com/moonbitlang/core/pull/767/files note we are fleshing out the error handling, so the error handling part still need some tweaks

Excellent, thank you, @bobzhang ! That helps a lot.  
Closing issues.
