### ISSUE TITLE
Feature request: Error 4120 - try adding a "!" to expression

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#666]
I got the following error in my code from the MoonBit compiler:

```
[4120] Error: The application might raise errors of type _/0, but it's not handled
    ╭─[/Users/glenn/src/github.com/gmlewis/moonbit-fonts/fonts/gen-path.mbt:7:3]
    │
  7 │ ╭─▶   iter_exn(
    ┆ ┆
 31 │ ├─▶   )
    │ │
    │ ╰───────── The application might raise errors of type _/0, but it's not handled
────╯
```

and was stuck for way longer than I should have been, when it dawned on me that this expression simply needed a trailing "!" in order to propagate the raised error to its parent.

So my feature request for the compiler is to please add a suggestion to `try adding a "!" to the expression`, as this might save myself and others a lot of frustration.

Thank you, and keep up the great work!

![feature-request-add-bang](https://github.com/moonbitlang/core/assets/6598971/98e9437d-b915-454a-9bdd-0552e062341d)

**Comment by Yu-zh** [comment]
Sorry about the error message being not informative. We will improve it as you suggested. Thanks!
