### ISSUE TITLE
moon -v test oddity

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#676]
Note below that the output of `moon -v test` first shows that a test passes:
`...::new_transition invalid commands ok`
and then later reports that the same test fails:
`...::new_transition invalid commands failed: FAILED: ...`

This seems rather odd and confusing.

```bash
$ moon version
moon 0.1.20240709 (6f94653 2024-07-09)

$ moon -v test
test .../sunburst-chart/parse-data.mbt::chars_to_string ok
test .../sunburst-chart/string.mbt::split_string ok
test .../sunburst-chart/string.mbt::compare_topic_values ok
test .../tests/plugin-functions_test.mbt::new_transition invalid commands ok
test .../tests/plugin-functions_test.mbt::new_transition valid commands ok
test .../tests/plugin-functions_test.mbt::new_transition invalid commands failed: FAILED: /Users/.../tests/plugin-functions_test.mbt:10:14-10:55 `"new_transition(some-unknown-long-command-name:yo) passed when it should have failed" == "unknown transition command"`
test .../tests/plugin-functions_test.mbt::new_transition valid commands failed: unknown transition command
Total tests: 7, passed: 5, failed: 2.
```

Here is the code for these tests:

```rust
test "new_transition invalid commands" {
  let expected_fails = ["", ":", "some-unknown-long-command-name:yo"]
  each_exn(
    expected_fails,
    fn(cmd) {
      try {
        @sunburst.new_transition(cmd)!
        raise "new_transition(\(cmd)) passed when it should have failed"
      } catch {
        e => @test.eq(e, "unknown transition command")!
      }
    },
  )!
}

test "new_transition valid commands" {
  let expected_success = [
    "ChangeTopicList:Age,Mortality,Medication", "FocusTo:", "FocusTo:51-60,True,Kinase Inhibitor",
  ]
  each_exn(expected_success, fn(cmd) { @sunburst.new_transition(cmd)! })!
}

fn each_exn[T, Err](arr : Array[T], func : (T) -> Unit!Err) -> Unit!Err {
  for i = 0; i < arr.length(); i = i + 1 {
    func(arr[i])!
  }
}
```

**Comment by Young-Flash** [comment]
`moon test` had been refactored recently, could you help verify again with the lastest moon?

**Comment by gmlewis** [comment]
Unfortunately, there appears to have been a regression in `moon test` with today's latest compiler.
It is not showing any error messages for failures.  See screenshot:

![hides-test-results-2024-08-28_07-57-32](https://github.com/user-attachments/assets/ae965ac4-7325-4b42-ab74-57c044cae9e1)

**Comment by gmlewis** [comment]
Update: if I run `rm -rf target`, then the problem goes away.

I think I might have a clue on the failure mechanism now... Here are the steps:

1. Start with a repo with no errors on a previous version of the compiler
2. Get the latest compiler using: `curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash`
3. Run: `moon update && moon install`
4. Run: `moon test`
5. RESULT: no output except that the number of `failed` results is now non-zero
6. Run: `rm -rf target`
7. Run: `moon test`
8. RESULT: now all the failures are shown

NOTE that in all of the above, there were _ZERO_ changes to the code itself.

So I'm thinking that whatever mechanism is cacheing test results also needs to cache the _VERSION_ of the compiler that generated those results so that if the compiler changes, all cached test results are discarded and it starts over with a clean slate.

Maybe you could create a CI/CD pipeline that tests this scenario by using an old compiler to test old code that used to pass all tests, but then your pipeline updates the compiler to the latest and you run tests again and ensure that it generates some output?

**Comment by gmlewis** [comment]
As for the original reported problem, I haven't seen that in a long time, and that seems to be fixed.
Thank you!
