### ISSUE TITLE
moon run problem on Mac

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#677]
When I run `moon -v run --target js --debug main` on a Mac M2 Max running Sonoma 14.4.1,
I get the error:

```bash
error: Permission denied (os error 13)
```

but I don't know what it is trying to run.

**Comment by qazxcdswe123** [comment]
Hi

I've tested it in a simple main function and did not encounter this issue. Could you please provide a case that can reproduce it? Or does it occur on every project?
Also maybe try reinstalling the toolchain?

`curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash`

**Comment by gmlewis** [comment]
I will continue to investigate. 
It would be nice though if the error message included the command that it was trying to execute so I could attempt to manually reproduce it.

**Comment by lijunchen** [comment]
Thanks for the feedback. In the latest version, it will print something like this:

```
$ moon version --all
moon 0.1.20240716 (057d907 2024-07-16) ~/.moon/bin/moon
moonc v0.1.20240716+26483df10 ~/.moon/bin/moonc
moonrun 0.1.20240716 (08bce9c 2024-07-16) ~/.moon/bin/moonrun
$ moon run main --target js
error: failed to execute: node /play/hello/target/js/release/build/main/main.js

Caused by:
    No such file or directory (os error 2)
```
