### ISSUE TITLE
ambiguous debug output for `List`

### ISSUE THREAD

**Issue by skylee03** [moonbitlang/core#687]
The current dubug output cannot accurately display the nested structure of lists.

For example:

```moonbit
fn main {
  let ls = @immut/list.of([
    @immut/list.of([1, 2, 3]),
    @immut/list.of([4, 5, 6]),
    @immut/list.of([7, 8, 9]),
  ])
  debug(ls) // 1, 2, 3, 4, 5, 6, 7, 8, 9
  println(ls) // List::[List::[1, 2, 3], List::[4, 5, 6], List::[7, 8, 9]]
}
```

It is better to change the output of `debug_write` to a format similar to the one of `to_string`.

---

Related PRs:
- #716 
- #719

**Comment by Yoorkin** [comment]
the output should be `[1,2,3,...,N]`

**Comment by skylee03** [comment]
> The result of `List::debug_write` should be `[1,2,3,...,N]`

I'll try to update it, then I can update #688 accordingly.

**Comment by skylee03** [comment]
I noticed that for other data structures, such as `Queue`, we used the result of `to_string` as the result of `debug_write`. Should we do the same for `List` to ensure consistency?

```moonbit
fn main {
  let q = @queue.of([1, 2, 3])
  println(q) // Queue::[1, 2, 3]
  debug(q) // Queue::[1, 2, 3]
}
```

**Comment by qazxcdswe123** [comment]
Shouldn't the `debug_write` also show the type?

> The result of List::debug_write should be [1,2,3,...,N]

or `List::[1,2,3,...,N]`

@Yoorkin

**Comment by Yoorkin** [comment]
> Should the `debug_write` also show the type?
> 
> > The result of List::debug_write should be [1,2,3,...,N]
> 
> or `List::[1,2,3,...,N]`
> 
> @Yoorkin

There will be some changes to the built-in `Debug` and `Show` traits, so we could fix these behaviors later.

**Comment by skylee03** [comment]
The `Debug` trait has been removed and the output of `println` looks fine. Therefore, this issue can be considered fixed.
