### ISSUE TITLE
Proposal: A New Type for Unicode Scalar Value

### ISSUE THREAD

**Issue by zxch3n** [moonbitlang/core#76]
`Char` is one byte and may not be a valid Unicode scalar value. The new type (maybe we can call it Rune like Go) is 32bit and stands for a valid Unicode scalar value.

- It can make converting a String to/from a UTF-16/UTF-32 easier
- It makes the interactions between js strings easier. For example, if you emit a string-related event from Moonbit to js, the length and index inside the event need to be converted from UTF-8 to UTF-16
- It makes handling tasks like moving a cursor on a string easier, which should not be based on UTF-8 index

**Comment by bobzhang** [comment]
@zxch3n note Char is not Byte in MoonBit, it is Int

**Comment by zxch3n** [comment]
@bobzhang The value type of `s[0]` is Char when s is a String. But it's actually a byte from a UTF-8 string, right? The behavior here might be confusing.

**Comment by bobzhang** [comment]
@zxch3n we decided to follow the same semantics of Js/Java. the String is utf16 encoded, char is Int internally.

> there should be a special iterator method that returns Char

we will provide such method
