### ISSUE TITLE
`min_value` for Double is not idiomatic

### ISSUE THREAD

**Issue by qazxcdswe123** [moonbitlang/core#885]
Currently, the min value for double is

```
let min_val : Double = 0x1L.reinterpret_as_double()
  inspect!(@double.min_value(), content="5.0e-324")
```

For me, the more idiomatic value would be

```
let min_val : Double = 4503599627370496L.reinterpret_as_double()
0 00000000001 0000000000000000000000000000000000000000000000000000 // bit value
  inspect!(@double.min_value(), content="2.2250738585072014e-308")
```

For example: https://doc.rust-lang.org/std/primitive.f64.html#associatedconstant.MIN_POSITIVE

Also probably separate MIN and MIN_POSITIVE?

Probably related: https://github.com/moonbitlang/core/pull/882

**Comment by yj-qin** [comment]
Should we rename the `min_norm` to `min_positive`, and make the MIN equal to -MAX?
