### ISSUE TITLE
Proposal: replace the naive quick sort for vec with sort for array

### ISSUE THREAD

**Issue by yjl9903** [moonbitlang/core#89]
In this pr #72 , author implemented an optimized quick sort algorithm like the `std:sort` in C++

But for vec, it already has a naive quick sort implementation

https://github.com/moonbitlang/core/blob/bcb5d5cbf99c9adeabc22485e10fd184f7400322/vec/vec.mbt#L619-L639

I think we can replace the vec sort with directly using the sort impl from array module, not implementing it twice.

**Comment by yjl9903** [comment]
I am trying to contribute, but I encountered a problem

`self.buf.0` is `Array[UnsafeMaybeUninit[T]]`, is it possible "casting" it to `Array[T]` (for we can ensure self.buf from 0 to self.len - 1 does have value)? Or any other possible solutions?

<img width="960" alt="image" src="https://github.com/moonbitlang/core/assets/30072175/ebc3e35c-6a6b-40e7-80db-df4453e58167">

**Comment by bobzhang** [comment]
> self.buf.0 is Array[UnsafeMaybeUninit[T]], is it possible "casting" it to Array[T]

This is possible in the wasm backend, the wasm will have its own verification layer.
You can define a local trait and use generics to share the code?

**Comment by yjl9903** [comment]
@bobzhang Thanks. But if I did not misunderstand, there should be a generic trait here which `Array[T]` and `Vec[T]` should implement? But moonbit seems not support it now?

<img width="534" alt="image" src="https://github.com/moonbitlang/core/assets/30072175/19dde9c2-f05b-48a8-a744-6175732aae46">

> https://github.com/moonbitlang/core/blob/main/array/sort.mbt

**Comment by Lampese** [comment]
#112 I think the discussion in this PR might be helpful.

**Comment by Lampese** [comment]
#168

**Comment by bobzhang** [comment]
done in master
