### ISSUE TITLE
One Problem About mut

### ISSUE THREAD

**Issue by Kaida-Amethyst** [moonbitlang/core#967]
The following code is work.

```
  // let mut numbers : Array[Int] = []; // Warning message: mutability is never used
  let numbers : Array[Int] = [];
  numbers.push(1)
  numbers.push(2)
  numbers.push(3)
  println(numbers)
```

`numbers` is not marked by `mut`, but we still could push elements into it. It is different with rust.

I wonder if it is ok in moonbit. However, if it is ok, why we need `mut` keyword？

**Comment by Yu-zh** [comment]
The concept of mutability in MoonBit is simpler than in Rust. When you have declaration
```
let mut numbers : Array[Int] = []
```
it means that the variable `numbers` is a reference to an array, and you can mutate what `numbers` refers to like:
```
numbers = [1, 2, 3]
```

**Comment by Kaida-Amethyst** [comment]
> The concept of mutability in MoonBit is simpler than in Rust. When you have declaration
> 
> ```
> let mut numbers : Array[Int] = []
> ```
> 
> it means that the variable `numbers` is a reference to an array, and you can mutate what `numbers` refers to like:
> 
> ```
> numbers = [1, 2, 3]
> ```
> 
> When you do the `push`, it changes the contents of the array but doesn't change the value of `numbers`, which is still the reference that points to the original array.

I think it's weird, because if so, why we need `mut`?

look at the following code:

```
  // let i = 0
  // i = 1 // Error: i is not mutable
  let w = [0]
  w[0] = 1 // Ok
  println(w[0])
```

**Comment by Yu-zh** [comment]
You are right because the `mut` keyword is not strictly required for the expressiveness of MoonBit. You can always use an array or the `Ref` type for mutability, for example:

```
fn main {
  let x: Ref[Int] = { val: 1 }
  x.val = 2
}
```
But it's cumbersome, so we provide the `mut` keyword to make it simpler.

**Comment by Kaida-Amethyst** [comment]
> You are right because the `mut` keyword is not strictly required for the expressiveness of MoonBit. You can always use an array or the `Ref` type for mutability, for example:
> 
> ```
> fn main {
>   let x: Ref[Int] = { val: 1 }
>   x.val = 2
> }
> ```
> 
> But it's cumbersome, so we provide the `mut` keyword to make it simpler for creating, updating, and accessing the mutable variable.

Haha, I understand, Thank you for your response. ^^
