### ISSUE TITLE
mooncakes.io reports false error message

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#979]
On this page: https://mooncakes.io/docs/#/gmlewis/spin-moonbit-sdk/
mooncakes.io is reporting the error:

> Failed to build with the latest Moon
> The previously built documentation for this package will be displayed on this page.

however, the package builds and tests fine with the latest `moon` compiler:

```
$ moon version --all
moon 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moon
moonc v0.1.20240910+3af041b9a ~/.moon/bin/moonc
moonrun 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moonrun

$ moon test
Total tests: 3, passed: 3, failed: 0.
```

**Comment by Yoorkin** [comment]
This is because the document generator, moondoc, crashed while building spin-moonbit-sdk. We will fix this before next week. Thank you.

**Comment by Yoorkin** [comment]
fixed
