### ISSUE TITLE
Perferred way to concatenate an array of characters

### ISSUE THREAD

**Issue by NKID00** [moonbitlang/core#989]
`Show::to_string` hides `Char::to_string` and joining an array of `Char` produces a messy result unlike Python (tho there's no builtin "char" in Python). Is this intended? If so, what is the perferred way to concatenate an array of characters? There seems to be no such method to collect an array or iterator into a string like Rust and folding it is quite tedious.

```moonbit
println(['1', '2', '3'].to_string()) // ['1', '2', '3']
println(['1', '2', '3'].join("")) // '1''2''3'
println(['1', '2', '3'].fold(init="", fn(s, c) { s + c.to_string() })) // 123
```

**Comment by Yoorkin** [comment]
The most effective way is 

```
  let array = ['1','2','3','4']
  let buf = Buffer::new()
  array.each(fn(x){ buf.write_char(x) })
  let str = buf.to_string()
  println(str)
```

Maybe we can implement it as `String::of` and `String::from_array`.

The behavior of `Array::join` is strange to me though. @hackwaly
