### ISSUE TITLE
 I want a programming language for Linux that allows me to create applications using a drag-and-drop interface, similar to using Delphi to drag and drop controls in Windows. Using C++ on Linux has a high barrier to entry and a steep learning curve, making it inaccessible for many users who simply don't have the time to study it.

### ISSUE THREAD

**Issue by xiaokentrl** [moonbitlang/core#990]
I want a programming language for Linux that allows me to create applications using a drag-and-drop interface, similar to using Delphi to drag and drop controls in Windows. Using C++ on Linux has a high barrier to entry and a steep learning curve, making it inaccessible for many users who simply don't have the time to study it.

**Comment by peter-jerry-ye** [comment]
Maybe your are looking for something like: [Cambalache](https://flathub.org/apps/ar.xjuan.Cambalache). We may provide gtk binding in the future with native backend.

The subject however is unrelated with this repository.
